config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  post "search_spots", to: "search#search_spots"
  post "search_experiences", to: "search#search_experiences"
  post "search_bookmarks", to: "search#search_bookmarks"

  get "pages/profile", to: "pages#profile"

  get "pages/settings", to: "pages#settings"

  resources :bookmarks, only: %i[index destroy]
  resources :visits, only: %i[destroy]
  resources :reviews, only: %i[edit update destroy]
  resources :links, only: %i[new create destroy]

  get "filter", to: "spots#filter_categories"

  resources :spots, only: %i[index show] do
    get "options", to: "spots#options"
    resources :bookmarks, only: %i[create]
    resources :visits, only: %i[create]
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
    resources :experiences, only: %i[index]
  end

  resources :experiences, only: %i[index show new create edit destroy] do
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
  searchkick

  has_many :reviews, as: :reviewable
  has_many :experiences, through: :links
  has_many :bookmarks
  has_many :visits
  has_many_attached :photos
  belongs_to :category

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :subtitle, presence: true
  validates :description, presence: true
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show options filter_categories]
  before_action :set_spot, only: %i[show]

  def index
    @spots = Spot.all
    @geoapify_hash = make_geoapify_request(ENV['GEOAPIFY_API_KEY'], '87.184.167.191') 
  end

  def show
    @marker =
      [{
        latitude: @spot.latitude,
        longitude: @spot.longitude,
        marker_html: render_to_string(partial: "marker"),
        name: @spot.name
      }]
    @bookmarks = Bookmark.where(spot: @spot)
    @bookmark = Bookmark.where(spot: @spot, user: current_user)
    @visits = Visit.where(spot: @spot)
    @events = Event.all
    links = Link.where(spot: @spot)
    @experiences = links.map(&:experience)
    @average_rating = average_rating

    @geoapify_hash = make_geoapify_request(ENV['GEOAPIFY_API_KEY'], '87.184.167.191') 
    @distance = @spot.distance_to([@geoapify_hash["latitude"], @geoapify_hash["longitude"]])
    @short_distance = @distance.round(2)
  end

  def options
    @visit = Visit.where(user: current_user, spot: params[:spot_id]).first
    @bookmark = Bookmark.where(user: current_user, spot: params[:spot_id]).first
    @review = Review.where(user: current_user, reviewable: params[:spot_id]).first if params[:spot_id]
    @review = Review.where(user: current_user, reviewable: params[:experience_id]).first if params[:experience_id]
  end

  def filter_categories
    @categories = Category.all
  end

  private

  def average_rating
    rating = 0
    @spot.reviews.each { |review| rating += review.rating }
    rating = rating.to_f / @spot.reviews.count
  end

  def set_spot
    @spot = Spot.find(params[:id])
  end

  def client_ip
    request.remote_ip
  end

  def make_geoapify_request(api_key, ip_address)
    uri = "https://api.geoapify.com/v1/ipinfo?ip=#{ip_address}&apiKey=#{api_key}"

    response = HTTParty.get(uri)
    parsed_response = JSON.parse(response.body)
    return parsed_response["location"]
    rescue StandardError => error
    puts "Error (#{ error.message })"
  end

  def spot_params
  params.require(:spot).permit(:search, :category, :distance)
  end

end

app/views/spots/_card_spot.html.erb
<div class="relative w-full snap-center">
  <%= link_to spot_path(spot) do %>
    <div class="absolute z-50 h-full w-10/12"></div>
  <% end %>
  <div class="relative">
    <div
      class="
        absolute flex w-full items-center justify-between px-3 pt-3 align-middle
      "
    >
      <p
        class=" <%= category_color_class(spot.category) %>
          text-description rounded-full px-4 py-1 font-semibold text-white
          shadow-lg
        "
      ><%= spot.category.name %></p>

      <div>
        <% bookmark = Bookmark.where(user: current_user, spot: spot).first %>
        <% if bookmark %>
          <%= button_to bookmark_path(spot), method: :delete, class: "w-full" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
              class="h-9 w-7 text-teal-400"
            >
              <path
                fill-rule="evenodd"
                d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z"
                clip-rule="evenodd"
              />
            </svg>
          <% end %>
        <% else %>
          <%= button_to spot_bookmarks_path(spot), class: "w-full" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="2"
              stroke="white"
              class="h-9 w-7"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
              />
            </svg>
          <% end %>
        <% end %>

      </div>
    </div>
    <%= cl_image_tag(
      spot.photos.first.key,
      class: "h-bigcardheight aspect-square w-full rounded-xl",
      alt: "image of #{spot.name}",
    ) %>
  </div>
  <div class="mt-4">
    <div class="flex items-center justify-between ">
      <p class="text-s font-semibold"><%= spot.name %></p>
      <p class="text-description flex items-center align-middle font-light">
        <% rating = 0 %>
        <% spot.reviews.each { |review| rating += review.rating } %>
        <% rating = rating.to_f / spot.reviews.count %>
        <p class="text-description flex items-center align-middle font-light">
          <% if rating.nan? %>
            0
          <% else %>
            <%= rating.round(1) %>
          <% end %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="ml-2 h-4 w-4 pb-px text-teal-400"
        >
          <path
            fill-rule="evenodd"
            d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
            clip-rule="evenodd"
          />
        </svg>
      </p>
    </div>
    <div class="flex items-center justify-between">
      <p class="text-description w-2/3 font-light"><%= spot.subtitle %></p>
      <p class="text-description font-light"> <%= spot.distance_to([@geoapify_hash["latitude"], @geoapify_hash["longitude"]]).round(2) %> <%= "km away" %> </p>
    </div>
  </div>
</div>

app/views/spots/_desktop_card_spot.html.erb
<div class="relative">
  <%= link_to spot_path(spot) do %>
    <div class="absolute z-30 h-full w-10/12"></div>
  <% end %>
  <div class="relative">
    <div
      class="
        absolute flex w-full items-center justify-between px-3 pt-3 align-middle
      "
    >
      <p
        class=" <%= category_color_class(spot.category) %>
          text-description rounded-full px-4 py-1 font-semibold text-white
          shadow-lg
        "
      ><%= spot.category.name %></p>

      <div>
        <% bookmark = Bookmark.where(user: current_user, spot: spot).first %>
        <% if bookmark %>
          <%= button_to bookmark_path(spot), method: :delete, class: "w-full" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
              class="h-9 w-7 text-teal-400"
            >
              <path
                fill-rule="evenodd"
                d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z"
                clip-rule="evenodd"
              />
            </svg>
          <% end %>
        <% else %>
          <%= button_to spot_bookmarks_path(spot), class: "w-full" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="2"
              stroke="white"
              class="h-9 w-7"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
              />
            </svg>
          <% end %>
        <% end %>

      </div>
    </div>
    <%= cl_image_tag(
      spot.photos.first.key,
      class: "h-72 aspect-square w-full rounded-xl",
      alt: "image of #{spot.name}",
    ) %>
  </div>
  <div class="mt-4">
    <div class="flex items-center justify-between ">
      <p class="text-s font-semibold"><%= spot.name %></p>
      <p class="text-description flex items-center align-middle font-light">
        <% rating = 0 %>
        <% spot.reviews.each { |review| rating += review.rating } %>
        <% rating = rating.to_f / spot.reviews.count %>
        <p class="text-description flex items-center align-middle font-light">
          <% if rating.nan? %>
            0
          <% else %>
            <%= rating.round(1) %>
          <% end %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="ml-2 h-4 w-4 pb-px text-teal-400"
        >
          <path
            fill-rule="evenodd"
            d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
            clip-rule="evenodd"
          />
        </svg>
      </p>
    </div>
      <p class="text-description font-light"> <%= spot.distance_to([@geoapify_hash["latitude"], @geoapify_hash["longitude"]]).round(2) %> <%= "km away" %> </p>
  </div>
</div>

app/views/spots/_marker.html.erb
<%= image_tag "spotz_symbol.png" %>

app/views/spots/index.html.erb
<div class="flex xl:hidden">
  <div class="h-9 w-9 rounded-full bg-teal-400 text-teal-400">.</div>
  <div class="ml-2 text-4xl font-bold">spot<span class="text-teal-400">z</span></div>
</div>

<div id="desktop" class="mt-20 hidden xl:block">
  <%= form_with url: search_spots_path, method: :post, class: "flex justify-between items-center gap-2 mb-4 mt-28 pb-2 " do |form| %>
    <div>
      <%= form.text_field :search, placeholder: "Find a spot...",  class: "w-72 rounded-lg border-[1px] border-solid border-slate-400 px-4 py-2 hover:drop-shadow-md" %>
      <%= form.submit :search, class: "rounded-lg bg-teal-400 border-[1px] border-solid border-teal-400 font-semibold text-white px-4 py-2 cursor-pointer" %>
    </div>
    <div>
      <%= form.select :category, 
        options_for_select(Category.all.map { |cat| [cat.name, cat.id] }.insert(0, ["Category", ""])), 
        {},
        { class: "cursor-pointer w-40 rounded-lg border-[1px] border-solid border-slate-400 px-4 py-2 hover:drop-shadow-md text-slate-600" } %>

      <%= form.select :distance, 
        [["< 1km", 1], ["< 5km", 5], ["< 15km", 15], ["< 25km", 25], ["< 50km", 50]].insert(0, ["Distance", ""]), 
        {}, 
        { class: "w-40 cursor-pointer  rounded-lg border-[1px] border-solid border-slate-400 px-4 py-2 hover:drop-shadow-md text-slate-600" } %>

      <%= form.select :rating, 
        ["> 1 star", "> 2 stars", "> 3 stars", "> 4 stars", "5 stars"].insert(0, ["Rating", ""]), 
        {}, 
        { class: "w-40 rounded-lg border-[1px] border-solid border-slate-400 cursor-pointer px-4 py-2 hover:drop-shadow-md text-slate-600" } %>
    </div>
  <% end %>
  <div id="spots">
    <%= render "pages/desktop_spot_grid", spots: @spots %>
  </div>
</div>

<div id="mobile" class="xl:hidden" data-controller="item-toggle">
  <div class="top-0 z-10 bg-white pb-2 pt-2">
    <%= render "searchbar" %>
    <div class="mt-2 flex justify-evenly divide-x-2 divide-slate-200">
      <div
        class="
          mb-2 w-full cursor-pointer border-slate-200 pb-2 text-center text-xl font-light
          text-slate-400
        "
        data-action="click->item-toggle#showItem1"
        data-item-toggle-target="item1Header"
      >
        List
      </div>
      <div
        class="
          mb-2 w-full cursor-pointer border-slate-200 pb-2 text-center text-xl font-light
          text-slate-400
        "
        data-action="click->item-toggle#showItem2"
        data-item-toggle-target="item2Header"
      >
        Map
      </div>
    </div>
  </div>
  <div>
    <div id="item1" data-item-toggle-target="item1" class="hidden">
      <% @spots.sort_by(&:name).each do |spot| %>
        <div class="mb-8 mt-4">
          <%= render "card_spot", spot: spot %>
        </div>
      <% end %>
    </div>
    <div id="item2" data-item-toggle-target="item2" class="hidden">
      <div class="map-container">
        <div
          id="index"
          class="
            mb-4 mt-4 flex flex-col justify-center rounded-xl border border-b
            border-slate-200
          "
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        >
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spots/options.html.erb
<%= turbo_frame_tag "modal" do %>
  <div
    class="fixed inset-0 z-40 overflow-y-auto"
    aria-labelledby="modal-title"
    role="dialog"
    aria-modal="true"
  >
    <div
      class="
        flex min-h-screen w-full items-end justify-center p-0 px-4 pb-16 pt-4
        text-center
      "
    >
      <div
        class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
        aria-hidden="true"
      ></div>
      <span
        class="hidden sm:inline-block sm:h-screen sm:align-middle"
        aria-hidden="true"
      >&#8203;</span>
      <div
        class="
          -mx-4 mb-28 inline-block w-full transform overflow-hidden rounded-xl bg-white
          px-4 pb-4 pt-5 text-left align-bottom shadow-xl transition-all
        "
      >
        <div class="flex justify-between">
          <h1 class="mb-4 text-xl font-semibold text-gray-800">Options</h1>
          <%= link_to spot_path(params[:spot_id]), data: {turbo_frame: "_top"} do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-6"
            >
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"/>
            </svg>
          <% end %>
        </div>
        <div class="my-4">
          <% if @visit %>
            <%= button_to visit_path(params[:spot_id]), data: {turbo_frame: "_top"}, method: :delete, class: "w-full" do %>
              <%= render "shared/button_primary", text: "Visited" %>
            <% end %>
          <% else %>
            <%= button_to spot_visits_path, data: {turbo_frame: "_top"}, class: "w-full" do %>
              <%= render "shared/button_secondary", text: "Mark as visited" %>
            <% end %>
          <% end %>
        </div>
        <div class="my-4">
          <% if @review %>
            <div class="flex">
              <%= link_to edit_review_path(@review), data: {turbo_frame: "_top"}, class: "w-full" do %>
                <%= render "shared/button_secondary", text: "Edit review" %>
              <% end %>
              <%= link_to review_path(@review), data: {turbo_method: :delete, turbo_frame: "_top"}, class: "w-full ml-2" do %>
                <%= render "shared/button_delete", text: "Delete review" %>
              <% end %>
            </div>
          <% else %>
            <%= link_to new_spot_review_path, data: { turbo_frame: "modal" }, class: "w-full" do %>
              <%= render "shared/button_secondary", text: "Leave a review" %>
            <% end %>

          <% end %>
        </div>
        <div class="my-4">
          <%= render "shared/button_secondary", text: "Add to an experience" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/spots/show.html.erb
<div data-controller="swiper" class="relative">
  <!-- back button -->
  <%= link_to :back, class: "absolute top-10 z-50  flex" do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 16 16"
      fill="currentColor"
      class="size-8 rounded-full bg-slate-50 p-1 shadow-xl"
    >
      <path
        fill-rule="evenodd"
        d="M14 8a.75.75 0 0 1-.75.75H4.56l3.22 3.22a.75.75 0 1 1-1.06 1.06l-4.5-4.5a.75.75 0 0 1 0-1.06l4.5-4.5a.75.75 0 0 1 1.06 1.06L4.56 7.25h8.69A.75.75 0 0 1 14 8Z"
        clip-rule="evenodd"
      />
    </svg>

  <% end %>
  <!-- share button -->
  <div class="absolute right-0 top-10 z-50 flex">
    <svg
      data-controller="share"
      data-share-url-value="<%= spot_url(@spot) %>"
      data-action="click->share#share"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 16 16"
      fill="currentColor"
      class="size-8 z-50 flex rounded-full bg-slate-50 p-1 shadow-xl"
    >
      <path
        d="M12 6a2 2 0 1 0-1.994-1.842L5.323 6.5a2 2 0 1 0 0 3l4.683 2.342a2 2 0 1 0 .67-1.342L5.995 8.158a2.03 2.03 0 0 0 0-.316L10.677 5.5c.353.311.816.5 1.323.5Z"
      />
    </svg>
    <!-- elipsis vertical -->
    <%= link_to spot_options_path(@spot), data: { turbo_frame: "modal" }, class: "ml-2" do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 16 16"
        fill="currentColor"
        class="size-8 rounded-full bg-slate-50 p-1 shadow-xl"
      >
        <path
          d="M8 2a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM8 6.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM9.5 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z"
        />
      </svg>
    <% end %>
  </div>
  <!-- Slider main container -->
  <div class="swiper relative -mx-4 -mt-12 h-72">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper w-full ">
      <!-- Slides -->
      <%= @spot.photos.each do |photo| %>
        <div class="swiper-slide w-full bg-gradient-to-b">
          <%= cl_image_tag photo.key,
          class: "my-transparency-gradient h-full w-full object-cover" %>
        </div>
      <% end %>
    </div>
    <!-- If we need pagination -->
    <div class="swiper-pagination pb-4"></div>
    <!-- If we need navigation buttons -->
    <div class="swiper-button-prev">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 16 16"
        fill="white"
        class="rounded-full"
      >
        <path
          fill-rule="evenodd"
          d="M9.78 4.22a.75.75 0 0 1 0 1.06L7.06 8l2.72 2.72a.75.75 0 1 1-1.06 1.06L5.47 8.53a.75.75 0 0 1 0-1.06l3.25-3.25a.75.75 0 0 1 1.06 0Z"
          clip-rule="evenodd"
        />
      </svg>
    </div>
    <div class="swiper-button-next"><svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 16 16"
        fill="white"
        class="rounded-full"
      >
        <path
          fill-rule="evenodd"
          d="M6.22 4.22a.75.75 0 0 1 1.06 0l3.25 3.25a.75.75 0 0 1 0 1.06l-3.25 3.25a.75.75 0 0 1-1.06-1.06L8.94 8 6.22 5.28a.75.75 0 0 1 0-1.06Z"
          clip-rule="evenodd"
        />
      </svg>
    </div>
  </div>

  <div class="flex justify-between">
    <div>
      <div class="text-2xl font-bold"><%= @spot.name %></div>
      <div class="mt-1 flex items-center">
        <% if @average_rating.nan? %>
          0
        <% else %>
          <%= @average_rating.round(1) %>
        <% end %>
        <div class="ml-1 flex">
          <!-- star rating -->
          <div class="rating">
            <div class="rating-average">
              <div class="star-outer">
                <% if @average_rating.nan? %>
                  <div class="star-inner" style="width: 0%;">
                <% else %>
                  <div class="star-inner" style="width: <%= (@average_rating / 5) * 100 %>% ">
                <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- amount of reviews -->
        <div class="ml-1">(<%= @spot.reviews.count %>)</div>
        <div class="ml-1 text-teal-400">
          •
          <%= @short_distance %>
          km away
        </div>
      </div>
    </div>
    <!-- bookmark -->
    <% if @bookmark.first %>
      <%= button_to bookmark_path(@spot), method: :delete, class: "w-full" do %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="h-9 w-7 text-teal-400"
        >
          <path
            fill-rule="evenodd"
            d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z"
            clip-rule="evenodd"
          />
        </svg>
      <% end %>
    <% else %>
      <%= button_to spot_bookmarks_path(@spot), class: "w-full" do %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="2"
          stroke="black"
          class="h-9 w-7"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
          />
        </svg>
      <% end %>
    <% end %>
  </div>
  <!-- Metrics -->
  <div class="flex w-full justify-between border-b border-slate-200 py-4">
    <div class="w-32 flex-col px-4 py-2">
      <div class="text-center font-bold"><%= @bookmarks.count %></div>
      <div class="text-center">Bookmarks</div>
    </div>
    <div class="w-32 flex-col px-4 py-2">
      <div class="text-center font-bold"><%= @visits.count %></div>
      <div class="text-center">Visits</div>
    </div>
    <div class="w-32 flex-col px-4 py-2">
      <div class="text-center font-bold"><%= @experiences.count %></div>
      <div class="text-center">Experiences</div>
    </div>
  </div>
  <!-- Description -->
  <p class="border-b border-slate-200 py-4 text-slate-700"><%= @spot.description %></p>
</div>
<!-- Map Section -->
<div class="border-b border-slate-200 pb-4">
  <div
    class="
      mb-4 mt-8 flex h-56 w-full flex-col justify-center rounded-xl border border-b
      border-slate-200
    "
    data-controller="map"
    data-map-markers-value="<%= @marker.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  >
  </div>
  <div class="flex"><svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="currentColor"
      class="size-6"
    >
      <path
        fill-rule="evenodd"
        d="m11.54 22.351.07.04.028.016a.76.76 0 0 0 .723 0l.028-.015.071-.041a16.975 16.975 0 0 0 1.144-.742 19.58 19.58 0 0 0 2.683-2.282c1.944-1.99 3.963-4.98 3.963-8.827a8.25 8.25 0 0 0-16.5 0c0 3.846 2.02 6.837 3.963 8.827a19.58 19.58 0 0 0 2.682 2.282 16.975 16.975 0 0 0 1.145.742ZM12 13.5a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"
        clip-rule="evenodd"
      />
    </svg>
    <p class="ml-1"><%= @spot.address %></p>
  </div>
  <div class="my-4">
    <%= link_to "https://www.google.de/maps/search/#{@spot.address}" do %>
      <%= render "shared/button_primary", text: "Get directions" %>
    <% end %>
  </div>
</div>

<div class="mt-12">
  <div class="text-xl font-bold">Events near
    <span class="text-teal-400"><%= @spot.name %></span>
  </div>
  <%= render "shared/event_carousel", events: @events %>
</div>

<div class="my-4">
  <div class="text-xl font-bold">Reviews
    <span class="text-teal-400">(<%= @spot.reviews.count %>)</span>
  </div>
  <%= render "shared/review_carousel", reviews: @spot.reviews %>
  <%= link_to spot_reviews_path(@spot) do %>
    <%= render "shared/button_secondary", text: "View all reviews" %>
  <% end %>
</div>

<div class="mt-12 text-xl font-bold">Experiences
  <span class="text-teal-400">(<%= @experiences.length %>)</span>
</div>
<div class="divide-y-2 divide-gray-100">

  <% @experiences[0..1].each do |experience| %>
    <%= render "shared/experience", experience: experience %>
  <% end %>
</div>
<div class="mb-4">
  <%= link_to spot_experiences_path(@spot) do %>
    <%= render "shared/button_secondary", text: "View all experiences" %>
  <% end %>
</div>