config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  post "search_spots", to: "search#search_spots"
  post "search_experiences", to: "search#search_experiences"
  post "search_bookmarks", to: "search#search_bookmarks"

  get "pages/profile", to: "pages#profile"

  get "pages/settings", to: "pages#settings"

  resources :bookmarks, only: %i[index destroy]
  resources :visits, only: %i[destroy]
  resources :reviews, only: %i[edit update destroy]
  resources :links, only: %i[new create destroy]

  get "filter", to: "spots#filter_categories"

  resources :spots, only: %i[index show] do
    get "options", to: "spots#options"
    resources :bookmarks, only: %i[create]
    resources :visits, only: %i[create]
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
    resources :experiences, only: %i[index]
  end

  resources :experiences, only: %i[index show new create edit destroy] do
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
  end
end

app/views/shared/_button_delete.html.erb
<div
  class="
    flex h-11 w-full flex-col justify-center rounded-xl border-teal-400
    bg-red-400 align-middle font-bold text-white
  "
><div class="w-full text-center"><%= text %></div></div>

app/views/shared/_button_primary.html.erb
<div
  class="
    flex h-11 w-full flex-col justify-center rounded-xl border-teal-400
    bg-teal-400 align-middle font-bold text-white
  "
><div class="w-full text-center"><%= text %></div></div>

app/views/shared/_card_event.html.erb
<div class="mr-6 w-52 max-w-sm snap-center">
  <div class="relative">
    <div
      class="
        absolute flex w-full items-center justify-between px-3 pt-3 align-middle
      "
    >
      <div>
      </div>
    </div>

    <%= cl_image_tag(
      event.photo.key,
      class: "object-cover w-full aspect-square h-52 w-52 rounded-xl",
    ) %>
  </div>
  <div class="mt-4">
    <div class="flex items-center justify-between ">
      <p class="text-s font-semibold"><%= event.title %></p>
      <p class="text-description flex items-center align-middle font-light"><%= [0.9,1.3,4.2,3.7].sample %> <%= "km" %>
          <path
            fill-rule="evenodd"
            d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
            clip-rule="evenodd"
          />
        </svg>
      </p>
    </div>
      <p class="text-description font-light"> <%= event.date.strftime("%a,  %d %b-%y") %> <%= event.time.strftime("%I:%M %p") %></p>
  </div>
</div>

app/views/shared/_card_spot_experience.html.erb
<div class="relative my-4 flex h-28 w-full rounded-xl">
  <%= link_to spot_path(spot) do %>
    <div class="absolute h-full w-11/12"></div>
  <% end %>
  <%= cl_image_tag(
    spot.photos.first.key,
    class: "h-full w-1/3 rounded-lg object-cover",
  ) %>
  <div class="w-2/3">
    <div class="ml-4 flex h-full flex-col justify-between">
      <div>
        <div class="flex items-center justify-between ">
          <p class="text-s font-semibold"><%= spot.name %></p>
          <!-- trashcan -->
          <% if experience.user = current_user %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-5 text-red-600"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
              />
            </svg>

          <% end %>
        </div>
        <p class="text-description flex items-center align-middle font-light">3.5
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="mx-1 h-4 w-4 pb-px"
          >
            <path
              fill-rule="evenodd"
              d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
              clip-rule="evenodd"
            />
          </svg>
          <span class="text-teal-400">• 3.5km away</span>
        </p>
      </div>
      <p class="text-description font-light"><%= spot.description[0..70] %>...</p>
    </div>
  </div>
</div>

app/views/shared/_desktop_navbar.html.erb
<div  class="hidden xl:flex fixed top-0 w-screen z-50 bg-white shadow py-4 ">
<div  class="flex mx-auto items-center justify-between container" data-controller="dropdown-toggle">
  <div id="logo">
    <%= link_to root_path do %>
      <div class="flex">
        <div class="h-9 w-9 rounded-full bg-teal-400 text-teal-400">.</div>
        <div class="ml-2 text-2xl font-bold">spot<span class="text-teal-400">z</span></div>
      </div>
    <% end %>
  </div>
  <div id="links" class="flex gap-2">
    <%= link_to spots_path do %>
      <span class="px-4 py-3 text-lg  text-slate-800<% if current_page?(controller: '/spots', action: 'index') %> font-semibold <% else %>  rounded-full  hover:bg-slate-100 hover:text-slate-700<% end %>">Find Spots</span>
    <% end %>
      <%= link_to experiences_path do %>
        <span class="px-4 py-3 text-lg  text-slate-800<% if current_page?(controller: '/experiences', action: 'index') %> font-semibold <% else %>  rounded-full  hover:bg-slate-100 hover:text-slate-700<% end %>">Experiences</span>
      <% end %>
    <% if user_signed_in? %>
      <%= link_to bookmarks_path do %>
        <span class="px-4 py-3 text-lg  text-slate-800<% if current_page?(controller: '/bookmarks', action: 'index') %> font-semibold <% else %>  rounded-full  hover:bg-slate-100 hover:text-slate-700<% end %>">Bookmarks</span>
      <% end %>
    <% end %>
  </div>
  <div id="profile" class="relative z-50">
    <div data-action="click->dropdown-toggle#toggle" class="flex cursor-pointer items-center rounded-full border-[1px] border-solid border-slate-200 px-4 py-2 hover:drop-shadow-md">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="size-6 text-slate-600"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
        />
      </svg>
      <% if user_signed_in? %>
        <%= cl_image_tag(current_user.photo.key, class: "ml-2 h-8 w-8 rounded-full") %>
      <% else %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="<% if current_page?(controller: '/pages', action: 'profile') %> 2.5 <% else %> 1.5<% end %>"
          stroke="currentColor"
          class="ml-1 h-9 w-9 text-slate-600">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
          />
        </svg>
      <% end %>
    </div>
    <div data-dropdown-toggle-target="dropdown" class="hidden transition-all duration-300 transform origin-top-right -translate-y-2 scale-95">
      <div class="z-50 absolute right-0 top-2 w-56 mt-2 origin-top-right bg-white border border-slate-200 divide-y divide-slate-100 rounded-md shadow-lg outline-none" aria-labelledby="headlessui-menu-button-1" id="headlessui-menu-items-117" role="menu">
        <% if user_signed_in? %>
          <div class="px-4 py-3">         
            <p class="text-sm leading-5">Signed in as</p>
            <p class="text-sm font-medium leading-5 text-slate-900 truncate"><%= current_user.email %></p>
          </div>
          <div class="py-1">
          <%= link_to "Profile", pages_profile_path, class: "text-slate-700 hover:bg-slate-100 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left" %>
          <%= link_to "Settings", pages_profile_path, class: "text-slate-700 hover:bg-slate-100 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left" %>
        </div>
          <div class="py-1">
          <%= link_to "Sign out", destroy_user_session_path, method: "delete", class: "text-slate-700 hover:bg-slate-100 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left" %>
        </div>
      <% else %>
          <div class="py-1">
          <%= link_to "Log In", new_user_session_path, class: "text-slate-900 font-medium hover:bg-slate-100 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "text-slate-700 hover:bg-slate-100 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left" %>
    </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_event_carousel.html.erb
<div
  class="
    no-scrollbar -mx-4 my-4 inline-flex sm:max-xl:w-screen flex-nowrap overflow-x-auto
  "
>
  <div class="ml-4 flex">
    <% events.each do |event| %>
        <%= render "shared/card_event", event: event %>
    <% end %>
  </div>
</div>

app/views/shared/_experience.html.erb
<div class="py-4">

  <div class="flex items-center justify-between">
    <%= link_to experience_path(experience) do %>
      <div class="text-wrap font-bold leading-5"><%= experience.name %></div>
    <% end %>
    <div class="ml-6">
      <div class="text-description flex items-center font-light text-gray-400"><div><%= experience.user.username %></div>
        <div class="ml-3 h-9 w-9 rounded-full ring-2 ring-white">
          <%= cl_image_tag experience.user.photo.key, class: "h-9 w-9 rounded-full ring-2 ring-white"  %>
        </div>
      </div>
    </div>
  </div>

  <div
    class="
      no-scrollbar -mx-4 my-2 inline-flex w-screen snap-x flex-nowrap overflow-x-auto
    "
  >
    <div class="ml-4 flex">
      <% experience.spots.each do |spot| %>
        <div class="mr-1 h-14 w-14">
          <%= cl_image_tag(spot.photos.first.key,class: "h-full w-full",
          ) %>
        </div>
      <% end %>
    </div>
  </div>
  <%= link_to () do %>
    <div class="text-description text-wrap font-light"><%= experience.description %></div>
  <% end %>
</div>

app/views/shared/_experience_index.html.erb
    <% @experiences.each do |experience| %>
<div class="py-4">

  <%= link_to "#" do %>
  <div class="flex items-center justify-between">
      <div class="text-wrap font-bold leading-5"><%= experience.name %></div>
    <div class="ml-6">
      <div class="text-description flex items-center font-light text-gray-400"><div><%= experience.user.username %></div>
        <div class="ml-3 h-9 w-9 rounded-full ring-2 ring-white">


        </div>
      </div>
    </div>
  </div>

  <div
    class="
      no-scrollbar -mx-4 my-2 inline-flex w-screen snap-x flex-nowrap overflow-x-auto
    "
  >
    <div class="ml-4 flex">
        <div class="mr-1 h-14 w-14">
      <% experience.spots.each do |spot| %>
          <%= cl_image_tag(spot.photos.first.key)  %>
<% end %>
        </div>
    </div>
  </div>
    <div class="text-description text-wrap font-light"><%= experience.description %></div>
  <% end %>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_mobile_navbar.html.erb
<div
  class="
    fixed bottom-0 z-50 flex h-16 w-full items-center justify-around
    border-t border-t-teal-100 bg-white xl:hidden pb-3
  "
>
  <%= link_to root_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/pages', action: 'home') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6 <% if current_page?(controller: '/pages', action: 'home') %>text-teal-400
        <%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"
      />
    </svg>

  <% end %>

  <%= link_to spots_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/spots', action: 'index') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6
        <% if current_page?(controller: '/spots', action: 'index') %>text-teal-400<%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
      />
    </svg>
  <% end %>

  <%= link_to bookmarks_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/bookmarks', action: 'index') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6
        <% if current_page?(controller: '/bookmarks', action: 'index') %>text-teal-400<%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
      />
    </svg>
  <% end %>

  <%= link_to pages_profile_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/pages', action: 'profile') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6
        <% if current_page?(controller: '/pages', action: 'profile') %>text-teal-400<%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
      />
    </svg>
  <% end %>

</div>

app/views/shared/_navbar.html.erb
<div
  class="
    fixed bottom-0 z-50 flex h-16 w-full items-center justify-around border-t
    border-t-teal-100 bg-white pb-3
  "
>
  <%= link_to root_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/pages', action: 'home') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6 <% if current_page?(controller: '/pages', action: 'home') %>text-teal-400
        <%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"
      />
    </svg>

  <% end %>

  <%= link_to spots_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/spots', action: 'index') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6
        <% if current_page?(controller: '/spots', action: 'index') %>text-teal-400<%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
      />
    </svg>
  <% end %>

  <%= link_to bookmarks_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/bookmarks', action: 'index') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6
        <% if current_page?(controller: '/bookmarks', action: 'index') %>text-teal-400<%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
      />
    </svg>
  <% end %>

  <%= link_to pages_profile_path do %>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="<% if current_page?(controller: '/pages', action: 'profile') %> 2.5 <% else %> 1.5<% end %>"
      stroke="currentColor"
      class="
        size-6
        <% if current_page?(controller: '/pages', action: 'profile') %>text-teal-400<%
        end %>
      "
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
      />
    </svg>
  <% end %>

</div>

app/views/shared/_review.html.erb
<div class="w-bigcardwidth my-4 rounded-xl border border-slate-300 p-4">
  <p><%= review.content %></p>
  <div class="my-2 flex">
    <!-- star rating -->
    <% review.rating.times do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 16 16"
        fill="currentColor"
        class="size-3 text-teal-400"
      >
        <path
          fill-rule="evenodd"
          d="M8 1.75a.75.75 0 0 1 .692.462l1.41 3.393 3.664.293a.75.75 0 0 1 .428 1.317l-2.791 2.39.853 3.575a.75.75 0 0 1-1.12.814L7.998 12.08l-3.135 1.915a.75.75 0 0 1-1.12-.814l.852-3.574-2.79-2.39a.75.75 0 0 1 .427-1.318l3.663-.293 1.41-3.393A.75.75 0 0 1 8 1.75Z"
          clip-rule="evenodd"
        />
      </svg>
    <% end %>
  </div>
  <div class="flex items-center font-light text-slate-500">
    <div class="flex w-full items-center justify-between">
      <p><%= review.created_at.strftime('%d. %b %Y') %></p>
      <div class="flex items-center">
        <div class="mr-1"><%= review.user.username %></div>
        <div class="size-8 rounded-full ring-2 ring-white">
          <%= cl_image_tag(review.user.photo.key, class: "h-full w-full rounded-full") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_review_carousel.html.erb
<div
  class="
    no-scrollbar -mx-4 inline-flex w-screen snap-x flex-nowrap overflow-x-auto
  "
>
  <div class="flex">
    <% reviews[0..4].each do |review| %>
      <div class="ml-4">
        <%= render "shared/review", review: review %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_review_full.html.erb
<div class="my-4 w-full rounded-xl border border-slate-300 p-4">
  <p> <%= review.content %>
  </p>
  <div class="my-2 flex">
    <!-- star rating -->
    <% review.rating.times do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 16 16"
        fill="currentColor"
        class="size-3 text-teal-400"
      >
        <path
          fill-rule="evenodd"
          d="M8 1.75a.75.75 0 0 1 .692.462l1.41 3.393 3.664.293a.75.75 0 0 1 .428 1.317l-2.791 2.39.853 3.575a.75.75 0 0 1-1.12.814L7.998 12.08l-3.135 1.915a.75.75 0 0 1-1.12-.814l.852-3.574-2.79-2.39a.75.75 0 0 1 .427-1.318l3.663-.293 1.41-3.393A.75.75 0 0 1 8 1.75Z"
          clip-rule="evenodd"
        />
      </svg>
    <% end %>
  </div>
  <div class="flex items-center font-light text-slate-500">
    <div class="flex w-full items-center justify-between">
      <p><%= review.created_at.strftime('%d. %b %Y')  %></p>
      <div class="flex items-center">
        <div class="mr-1"><%= review.user.username %></div>
        <div class="size-8 rounded-full ring-2 ring-white">
          <%= cl_image_tag(review.user.photo.key, class: "h-full w-full rounded-full") %>
        </div>
      </div>
    </div>
  </div>
</div>