config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  post "search_spots", to: "search#search_spots"
  post "search_experiences", to: "search#search_experiences"
  post "search_bookmarks", to: "search#search_bookmarks"

  get "pages/profile", to: "pages#profile"

  get "pages/settings", to: "pages#settings"

  resources :bookmarks, only: %i[index destroy]
  resources :visits, only: %i[destroy]
  resources :reviews, only: %i[edit update destroy]
  resources :links, only: %i[new create destroy]

  get "filter", to: "spots#filter_categories"

  resources :spots, only: %i[index show] do
    get "options", to: "spots#options"
    resources :bookmarks, only: %i[create]
    resources :visits, only: %i[create]
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
    resources :experiences, only: %i[index]
  end

  resources :experiences, only: %i[index show new create edit destroy] do
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
  end
end

app/views/pages/_card_spot_home.html.erb
<div class="w-bigcardwidth relative mr-6 max-w-sm snap-center">
  <%= link_to spot_path(spot) do %>
    <div class="absolute z-50 h-full w-10/12"></div>
  <% end %>
  <div class="relative">
    <div
      class="
        absolute flex w-full items-center justify-between px-3 pt-3 align-middle
      "
    >
      <p
        class=" <%= category_color_class(spot.category) %>
          text-description rounded-full px-4 py-1 font-semibold text-white
          shadow-lg
        "
      ><%= spot.category.name %></p>

      <div>
        <% bookmark = Bookmark.where(user: current_user, spot: spot).first %>
        <% if bookmark %>
          <%= button_to bookmark_path(spot), method: :delete, class: "w-full" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="currentColor"
              class="h-9 w-7 text-teal-400"
            >
              <path
                fill-rule="evenodd"
                d="M6.32 2.577a49.255 49.255 0 0 1 11.36 0c1.497.174 2.57 1.46 2.57 2.93V21a.75.75 0 0 1-1.085.67L12 18.089l-7.165 3.583A.75.75 0 0 1 3.75 21V5.507c0-1.47 1.073-2.756 2.57-2.93Z"
                clip-rule="evenodd"
              />
            </svg>
          <% end %>

        <% else %>
          <%= button_to spot_bookmarks_path(spot), class: "w-full" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="2"
              stroke="white"
              class="h-9 w-7"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
              />
            </svg>
          <% end %>
        <% end %>

      </div>
    </div>

    <%= cl_image_tag(
      spot.photos.first.key,
      class: "object-fill w-bigcardwidth h-bigcardheight aspect-square rounded-xl",
    ) %>
  </div>
  <div class="mt-4">
    <div class="flex items-center justify-between ">
      <p class="text-s font-semibold"><%= spot.name %></p>
      <p class="text-description flex items-center align-middle font-light">
        <% rating = 0 %>
        <% spot.reviews.each { |review| rating += review.rating } %>
        <% rating = rating.to_f / spot.reviews.count %>
        <p class="text-description flex items-center align-middle font-light">
          <% if rating.nan? %>
            0
          <% else %>
            <%= rating.round(1) %>
          <% end %>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="#2DD4BF"
          class="ml-2 h-4 w-4 pb-px"
        >
          <path
            fill-rule="evenodd"
            d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
            clip-rule="evenodd"
          />
        </svg>
      </p>
    </div>
    <div class="flex items-center justify-between">
      <p class="text-description font-light"><%= spot.subtitle %></p>
      <p class="text-description font-light"> <%= spot.distance_to([@geoapify_hash["latitude"], @geoapify_hash["longitude"]]).round(2) %> <%= "km away" %> </p>
    </div>
  </div>
</div>

app/views/pages/_desktop_spot_grid.html.erb
<div class="my-4 hidden grid-cols-4 gap-8 gap-y-12 xl:grid 2xl:grid-cols-5" >
  <% spots.sort_by(&:name).each do |spot| %>
      <%= render "spots/desktop_card_spot", spot: spot %>
  <% end %>
</div>

app/views/pages/_review_profile.html.erb
<div class="my-4 w-full rounded-xl border border-slate-300 p-4">
  <p>
    <%= review.content %>
  </p>
  <div class="my-2 flex">
    <!-- star rating -->
    <% review.rating.times do %>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 16 16"
        fill="currentColor"
        class="size-3 text-teal-400"
      >
        <path
          fill-rule="evenodd"
          d="M8 1.75a.75.75 0 0 1 .692.462l1.41 3.393 3.664.293a.75.75 0 0 1 .428 1.317l-2.791 2.39.853 3.575a.75.75 0 0 1-1.12.814L7.998 12.08l-3.135 1.915a.75.75 0 0 1-1.12-.814l.852-3.574-2.79-2.39a.75.75 0 0 1 .427-1.318l3.663-.293 1.41-3.393A.75.75 0 0 1 8 1.75Z"
          clip-rule="evenodd"
        />
      </svg>
    <% end %>
  </div>
  <div class="flex items-center font-light text-slate-500">
    <div class="flex w-full items-center justify-between">
      <p><%= review.created_at.strftime("%d. %b %Y") %></p>
      <div class="flex items-center">
        <div class="mr-1"><%= review.reviewable.name[0..30]... %></div>
        <% if review.reviewable_type == "Spot" %>
          <div class="size-8 rounded-full ring-2 ring-white">
            <%= cl_image_tag(
              review.reviewable.photos.first.key,
              class: "rounded-full h-full w-full",
            ) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_searchbar.html.erb
<div
  data-controller="searchbar"
  class="my-8 rounded-full border border-gray-300 px-6 py-3"
  >
  <div class="flex items-center w-full relative">
    <div class="flex grow-0 items-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        fill="currentColor"
        class="size-7 grow-0"
      >
        <path
          fill-rule="evenodd"
          d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z"
          clip-rule="evenodd"
        />
      </svg>
      <div
        data-searchbar-target="text"
        data-action="click->searchbar#show"
        class="ml-4 h-10 grow flex-col"
        >
        <div class="font-semibold leading-5">Find spotz</div>
        <div class="text-description font-light leading-4">Explore like a local</div>
      </div>
    </div>
    <div class="flex items-center">
      <div data-searchbar-target="input" class="hidden grow">
        <%= form_with url: spots_path, method: :get, class: "h-10 search-bar w-64 flex items-center" do %>
          <%= text_field_tag :query, params[:query],
          class: "search-input border-white focus:ring-white focus:border-white text-xl",
          placeholder: "" %>
          <%= submit_tag "", class: "search-div fa-solid" %>
        <% end %>
      </div>
      <%= link_to () do %>
        <svg data-action="click->toggle#toggle"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="size-7 absolute right-0 top-1"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M10.5 6h9.75M10.5 6a1.5 1.5 0 1 1-3 0m3 0a1.5 1.5 0 1 0-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 0 1-3 0m3 0a1.5 1.5 0 0 0-3 0m-9.75 0h9.75"
          />
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_spot_carousel.html.erb
<div
  class="
    no-scrollbar -mx-4 mt-4 inline-flex w-screen  snap-x flex-nowrap overflow-x-auto
  "
>
  <div class="ml-4 flex">
    <% spots[0..10].sort_by(&:name).each do |spot| %>
      <%= link_to spot_path(spot) do %>
        <%= render "card_spot_home", spot: spot %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/experiment.html.erb
<!-- Slider main container -->
<div class="swiper relative -mx-4 -mt-12 h-72">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper w-full ">
    <!-- Slides -->
    <% 10.times do %>
      <div class="swiper-slide w-full bg-gradient-to-b">

        <img
          class="my-transparency-gradient h-full w-full object-cover"
          src="https://images.unsplash.com/photo-1603787935137-58167f55336f?q=80&w=1965&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
          alt="what"
        >
      </div>
    <% end %>
  </div>
  <!-- If we need pagination -->
  <div class="swiper-pagination pb-4"></div>
  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev mb-4">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="2"
      stroke="black"
      class="size-1 rounded-full bg-white p-1 shadow-xl"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M15.75 19.5 8.25 12l7.5-7.5"
      />
    </svg>

  </div>
  <div class="swiper-button-next mb-4"><svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="2"
      stroke="black"
      class="size-1 rounded-full bg-white p-1 shadow-xl"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="m8.25 4.5 7.5 7.5-7.5 7.5"
      />
    </svg>
  </div>
</div>

<div class="mt-4 flex justify-between">
  <div>
    <div class="text-2xl font-bold">Tempelhofer Feld</div>
    <div class="mt-1 flex items-center">
      4.3
      <div class="ml-1 flex">
        <% 5.times do %>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="h-4 w-4"
          >
            <path
              fill-rule="evenodd"
              d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
              clip-rule="evenodd"
            />
          </svg>
        <% end %>
      </div>
      <div class="ml-1">(412)</div>
      <div class="ml-1 text-slate-400">
        • 3.5km away</div>
    </div>
  </div>

  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke-width="2"
    stroke="black"
    class="h-9 w-7"
  >
    <path
      stroke-linecap="round"
      stroke-linejoin="round"
      d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0 1 11.186 0Z"
    />
  </svg>
</div>

app/views/pages/home.html.erb
<div class="flex xl:hidden">
  <div class="h-9 w-9 rounded-full bg-teal-400 text-teal-400">.</div>
  <div class="ml-2 text-2xl font-bold">spot<span class="text-teal-400">z</span></div>
</div>
<div class="mt-10 text-2xl font-medium  sm:text-xl xl:mb-6 xl:mt-32 ">Popular 
  <span class="text-teal-400">spotz</span>
  in your area
</div>

<%= render "desktop_spot_grid", spots: @spots[0..20] %>
<div class="xl:hidden">
  <%= render "spot_carousel", spots: @spots %>
</div>

<div class="mt-10 text-2xl font-medium  sm:text-xl xl:mb-6 xl:mt-32 ">
  <span class="text-teal-400">Events</span>
  near you
</div>
<%= render "shared/event_carousel", events: @events %>

<div class="mt-10 text-2xl font-medium  sm:text-xl xl:mb-6 xl:mt-32 ">Curated
  <span class="text-teal-400">Experiences</span>
</div>
<div class="divide-y-2 divide-gray-100">
  <% @experiences[0..1].each do |experience| %>
    <%= render "shared/experience", experience: experience %>
  <% end %>
</div>

<%= link_to experiences_path do %>
  <%= render "shared/button_secondary", text: "View all experiences" %>
<% end %>

app/views/pages/profile.html.erb
<div data-controller="toggle">
  <div class="">
      <div class="flex justify-between">
        <div class="flex">
          <div class="h-9 w-9 rounded-full bg-teal-400 text-teal-400">.</div>
          <div class="ml-2 text-4xl font-bold">profile</div>
        </div>
        <div>
          <div class="cursor-pointer" data-action="click->toggle#showItem" data-toggle-target="itemHeader">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-9 text-slate-500"
              data-toggle-target="itemHeader">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z"/>
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
            </svg>
          </div>
        </div>
      </div>
  </div>


  <div class="relative mt-6 items-center justify-center p-1">
    <%= cl_image_tag(current_user.photo.key, class: "mx-auto h-40 w-40 rounded-full") %>
    <div class="flex justify-center">
      <div class="mt-2 text-center">
        <h2>@<%= current_user.username %></h2>
      </div>
    </div>
  </div>

  <div class="items-start ">
      <div id="item" data-toggle-target="item" class="hidden"
        class="fixed inset-0 overflow-y-auto"
        aria-labelledby="modal-title"
        role="dialog"
        aria-modal="true">
        <div class=
            "flex w-full items-start justify-center p-0 px-4 pb-16 pt-4
            text-center">
          <div
            class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
            aria-hidden="true"
          ></div>
          <span
            class="hidden sm:inline-block sm:h-screen sm:align-middle"
            aria-hidden="true"
          >&#8203;</span>
          <div
            class="
              -mx-4 inline-block w-full transform overflow-hidden rounded-xl bg-white
              px-4 pb-2 pt-5 text-left align-top shadow-xl transition-all" >
            <div class="flex justify-between">
              <h1 class="mb-4 text-xl font-semibold text-gray-800">Settings</h1>
              <%= link_to pages_profile_url, data: {turbo_frame: "_top"} do %>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="size-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"/>
                </svg>
              <% end %>
            </div>

            <div class="my-4">
              <%= render "shared/button_secondary", text: "Change Profile Picture" %>
            </div>

            <div class="my-4">
              <%= render "shared/button_secondary", text: "Change Password" %>
            </div>

            <div class="my-4">
              <%= render "shared/button_secondary", text: "Share SPOTZ, get $100" %>
            </div>

            <div class="my-4">
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
              <%= render "shared/button_primary", text: "Log out" %>
              <% end %>
            </div>

          </div>

        </div>
      </div>
  </div>

    <div class="space-around mb-8 mt-4 flex justify-evenly text-sm text-gray-600">
      <div>
        <span
          data-action="click->toggle#showVisits"
          data-toggle-target="visitsHeader"
          class="cursor-pointer"
        >Visits (<%= @visits.count %>)</span>
      </div>
      <div>
        |
      </div>
      <div>
        <span
          data-action="click->toggle#showExperiences"
          data-toggle-target="experiencesHeader"
          class="cursor-pointer"
        >Experiences (<%= @experiences.count %>)</span>
      </div>
      <div>
        |
      </div>
      <div>
        <span
          data-action="click->toggle#showReviews"
          data-toggle-target="reviewsHeader"
          class="cursor-pointer"
        >Reviews (<%= @reviews.count %>)</span>
      </div>
    </div>

    <div>
      <div id="visits" data-toggle-target="visits" class="hidden">
        <% @visits.each do |visit| %>
          <%= render "shared/card_spot_bookmark", spot: visit.spot %>
        <% end %>
      </div>

      <div id="experiences" data-toggle-target="experiences" class="hidden">
        <div class="divide-y-2 divide-gray-100">
          <% @experiences.each do |experience| %>
            <%= render "shared/experience", experience: experience %>
          <% end %>
        </div>
      </div>

    <div id="reviews" data-toggle-target="reviews" class="hidden">
      <% @reviews.each do |review| %>
        <%= render "review_profile", review: review %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/settings.html.erb
<%= turbo_frame_tag "modal" do %>
  <div
    class="fixed inset-0 z-40 overflow-y-auto"
    aria-labelledby="modal-title"
    role="dialog"
    aria-modal="true"
  >
    <div class=
        "flex min-h-screen w-full items-end justify-center p-0 px-4 pb-16 pt-4
        text-center">
      <div
        class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
        aria-hidden="true"
      ></div>
      <span
        class="hidden sm:inline-block sm:h-screen sm:align-middle"
        aria-hidden="true"
      >&#8203;</span>
      <div
        class="
          -mx-4 mb-28 inline-block w-full transform overflow-hidden rounded-xl bg-white
          px-4 pb-4 pt-5 text-left align-bottom shadow-xl transition-all
        "
      >
        <div class="flex justify-between">
          <h1 class="mb-4 text-xl font-semibold text-gray-800">Settings</h1>
          <%= link_to pages_profile_url, data: {turbo_frame: "_top"} do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12"/>
            </svg>
          <% end %>
        </div>

        <div class="my-4">
          <%= render "shared/button_secondary", text: "Change profile picture" %>
        </div>

        <div class="my-4">
          <%= render "shared/button_secondary", text: "Share SPOTZ, get $100" %>
        </div>

        <div class="my-4">
          <%= render "shared/button_delete", text: "Log out" %>
        </div>

      </div>
    </div>
  </div>
<% end %>