config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  post "search_spots", to: "search#search_spots"
  post "search_experiences", to: "search#search_experiences"
  post "search_bookmarks", to: "search#search_bookmarks"

  get "pages/profile", to: "pages#profile"

  get "pages/settings", to: "pages#settings"

  resources :bookmarks, only: %i[index destroy]
  resources :visits, only: %i[destroy]
  resources :reviews, only: %i[edit update destroy]
  resources :links, only: %i[new create destroy]

  get "filter", to: "spots#filter_categories"

  resources :spots, only: %i[index show] do
    get "options", to: "spots#options"
    resources :bookmarks, only: %i[create]
    resources :visits, only: %i[create]
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
    resources :experiences, only: %i[index]
  end

  resources :experiences, only: %i[index show new create edit destroy] do
    resources :reviews, only: %i[new create index]
    resources :links, only: %i[new create]
  end
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :reviews, as: :reviewable
  has_many :links, dependent: :destroy
  has_many :spots, through: :links
  accepts_nested_attributes_for :spots
  belongs_to :user

  validates :name, presence: true, length: { maximum: 85 }
  validates :description, length: { maximum: 256 }
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_experience, only: %i[show edit update destroy]

  def index
    @experiences = Experience.all
    return unless params[:spot_id]

    @spot = Spot.find(params[:spot_id])
    links = Link.where(spot: params[:spot_id])
    @experiences = links.map { |link| link.experience }
  end

  def show
    @average_rating = average_rating
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      redirect_to @experience, notice: 'Experience was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @experience.destroy
    redirect_to experiences_path
  end

  def edit
  end

  def update
    if @experience.update(experience_params)
      flash[:notice] = "Your experience was successfully updated."
      redirect_to experience_path(@experience)
    else
      render :edit
    end
  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end

  def experience_params
    params.require(:experience).permit(:name, :description)
  end

  def average_rating
    rating = 0
    @experience.reviews.each { |review| rating += review.rating }
    rating = rating.to_f / @experience.reviews.count
  end
end

app/views/experiences/_card_spot_experience.html.erb
<div class="relative my-4 flex h-28 w-full rounded-xl">
  <%= link_to spot_path(spot) do %>
    <div class="absolute h-full w-11/12"></div>
  <% end %>
  <%= cl_image_tag(
    spot.photos.first.key,
    class: "h-full w-1/3 rounded-lg object-cover",
  ) %>
  <div class="w-2/3">
    <div class="ml-4 flex h-full flex-col justify-between">
      <div>
        <div class="flex items-center justify-between ">
          <p class="text-s font-semibold"><%= spot.name %></p>
          <!-- trashcan -->
          <% link = Link.where(spot: spot, experience: experience).first %>
          <% if experience.user == current_user %>
            <%= button_to link_path(link), method: :delete do %>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="currentColor"
                class="size-5 text-red-600"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
                />
              </svg>
            <% end %>
          <% end %>
        </div>
        <p class="text-description flex items-center align-middle font-light">
        <% rating = 0 %>
        <% spot.reviews.each { |review| rating += review.rating } %>
        <% rating = rating.to_f / spot.reviews.count %>
        <p class="text-description flex items-center align-middle font-light">
          <% if rating.nan? %>
            0
          <% else %>
            <%= rating.round(1) %>
          <% end %>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="mx-1 h-4 w-4 pb-px text-teal-400"
          >
            <path
              fill-rule="evenodd"
              d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.006 5.404.434c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.434 2.082-5.005Z"
              clip-rule="evenodd"
            />
          </svg>
        </p>
      </div>
      <p class="text-description font-light"><%= spot.description[0..70] %>...</p>
    </div>
  </div>
</div>

app/views/experiences/index.html.erb
<div id="desktop" class="hidden xl:block">
  <div class="mb-8 mt-28 border-b-[1px] border-solid border-slate-200 pb-2 ">Browse by</div>
  <% @experiences.each do |experience| %>
    <%= render "shared/experience", experience: experience %>
  <% end %>
</div>
<div id="mobile" class="xl:hidden">

  <!--HEADER-->
  <div class="mt-8 flex items-center justify-between">
    <div class="flex">
      <div class="h-9 w-9 rounded-full bg-teal-400 text-teal-400">.</div>
      <div class="ml-2 flex text-4xl font-bold">experiences</div>
    </div>
  </div>

  <%= link_to new_experience_path(@experiences), class: "xl:hidden" do %>
    <div class="mb-2 mt-6 border-b-2 border-gray-100 pb-6">
      <%= render "shared/button_primary", text: "Add an experience" %>
    </div>
  <% end %>

  <div class="divide-y-2 divide-gray-100">
    <% @experiences.each do |experience| %>
      <%= render "shared/experience", experience: experience %>
    <% end %>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="my-4 text-2xl font-bold">
  <h1>Create an experience</h1>
</div>
<div class="text-xl">
  <%= simple_form_for(@experience) do |f| %>
  <div class="my-4">
    <%= f.input :name, placeholder: 'name', label:false, input_html: { class: 'rounded-lg w-full border-slate-300' } %>
  </div>
  <div class="my-4">
    <%= f.input :description, placeholder: "describe the experience...", label:false, input_html: { class: 'rounded-lg w-full border-slate-300' }%>
  </div>
    <div class="my-4">
  <%= button_tag(type: 'submit', class: "w-full") do %>
    <%= render "shared/button_primary", text: "Create experience" %>
  <% end %>
  </div>
  <% end %>
</div>

app/views/experiences/show.html.erb
<div class="flex h-full flex-col justify-between divide-y-2 divide-gray-100">
  <div class="pb-4">
    <div class="flex items-start justify-between">
      <p class="w-2/3 text-xl font-semibold"><%= @experience.name %></p>
      <% if @experience.user == current_user %>
        <div class="flex items-start" data-controller="experience">
          <svg
            data-controller="share"
            data-share-url-value="<%= experience_url(@experience) %>"
            data-action="click->share#share"
            data-experience-target="share"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 16 16"
            fill="currentColor"
            class="size-7 mr-2 hidden"
          >
            <path
              d="M12 6a2 2 0 1 0-1.994-1.842L5.323 6.5a2 2 0 1 0 0 3l4.683 2.342a2 2 0 1 0 .67-1.342L5.995 8.158a2.03 2.03 0 0 0 0-.316L10.677 5.5c.353.311.816.5 1.323.5Z"
            />
          </svg>
          <%= link_to experience_path(@experience), data: { turbo_method: :delete } do %>
            <svg
              data-experience-target="delete"
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="size-6 mr-2 hidden text-red-600"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0"
              />
            </svg>
          <% end %>
          <svg
            data-experience-target="options"
            data-action="click->experience#toggleUser"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 6.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 12.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5ZM12 18.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5Z"
            />
          </svg>
        </div>
      <% else %>
        <svg
          data-controller="share"
          data-share-url-value="<%= experience_url(@experience) %>"
          data-action="click->share#share"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 16 16"
          fill="currentColor"
          class="size-6"
        >
          <path
            d="M12 6a2 2 0 1 0-1.994-1.842L5.323 6.5a2 2 0 1 0 0 3l4.683 2.342a2 2 0 1 0 .67-1.342L5.995 8.158a2.03 2.03 0 0 0 0-.316L10.677 5.5c.353.311.816.5 1.323.5Z"
          />
        </svg>

      <% end %>
    </div>
    <div class="text-description mt-1 flex items-center">
      <% if @average_rating.nan? %>
        0
      <% else %>
        <%= @average_rating.round(1) %>
      <% end %>
      <div class="ml-1 flex">
        <!-- star rating -->
          <div class="rating">
            <div class="rating-average">
              <div class="star-outer">
                <% if @average_rating.nan? %>
                  <div class="star-inner" style="width: 0%;">
                <% else %>
                  <div class="star-inner" style="width: <%= (@average_rating / 5) * 100 %>% ">
                <% end %>
                </div>
              </div>
            </div>
          </div>
      </div>
      <p class="text-slate-500">
        (<%= @experience.reviews.length %>)
      </p>
      <p class="text-description ml-1 text-teal-400">•
        <%= @experience.spots.count %>
        spotz</p>
    </div>
    <div class="flex justify-between">
      <div class="text-description mt-1 flex items-center font-light"><div class="text-gray-400">created by
          <%= @experience.user.username %></div>
        <div class="size-6 ml-1 mr-3 rounded-full ring-2 ring-white">
          <%= cl_image_tag @experience.user.photo.key,
          class: "rounded-full size-6 ring-2 ring-white" %>
        </div>
      </div>
      <div>
        <%= link_to experience_reviews_path(@experience) do %>
          <p class="text-description mt-1 flex items-center">See reviews</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="py-4"><%= @experience.description %></div>
  <div class="py-4">
    <% @experience.spots.each do |spot| %>
      <%= render "card_spot_experience", experience: @experience, spot: spot %>
    <% end %>
    <% if @experience.user == current_user %>
      <%= link_to new_experience_link_path(@experience) do %>
        <div class="flex justify-center py-4"><svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="size-6 text-slate-400"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 4.5v15m7.5-7.5h-15"
            />
          </svg>
        </div>
      <% end %>
    <% end %>
  </div>
</div>